name: Benchmark runner

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 7 * * * # every day at 7am UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: |
          corepack enable
          corepack prepare pnpm --activate
          corepack prepare yarn --activate
      - uses: oven-sh/setup-bun@v2
      - run: bun -v
      - run: pnpm install
      - run: pnpm run benchmark
      - name: Commit changes
        run: |
          git config --local user.email "bozonedouard@gmail.com"
          git config --local user.name "Edouard Bozon"
          git add .
          git status -s
          git diff --exit-code && git commit -m "chore: update results"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
